name: tfp
channels:
  - conda-forge
dependencies:
  - pyarrow
  - psutil
  - ipython
  - blosc
  - python-blosc
  - numba
  - uproot
  - pandas
  - matplotlib
  - scipy
  - jupyter
  - tqdm
  - cloudpickle
  - jinja2
#  - tensorflow
  - lz4
  - pip
  - pythia8
  - cudatoolkit==10.0.130
  - cupti
  - cudnn
  - pip:
      - coffea
      - tensorflow==2.0.0
      - tensorflow_probability==0.8.0
      - tensorflow-gpu
